#!/bin/bash

# ONNX Runtime 安装脚本
# 作者: Generated by Copilot
# 日期: 2025-07-13

set -e

echo "========================================"
echo "ONNX Runtime 安装脚本"
echo "========================================"

# 检测系统架构
ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
    ARCH_NAME="x64"
elif [ "$ARCH" = "aarch64" ]; then
    ARCH_NAME="aarch64"
else
    echo "错误: 不支持的架构 $ARCH"
    echo "支持的架构: x86_64, aarch64"
    exit 1
fi

# ONNX Runtime版本
VERSION="1.16.3"
PACKAGE_NAME="onnxruntime-linux-${ARCH_NAME}-${VERSION}"
DOWNLOAD_URL="https://github.com/microsoft/onnxruntime/releases/download/v${VERSION}/${PACKAGE_NAME}.tgz"

echo "系统架构: $ARCH ($ARCH_NAME)"
echo "ONNX Runtime 版本: $VERSION"
echo "下载地址: $DOWNLOAD_URL"

# 检查是否已经安装
if [ -f "/usr/local/include/onnxruntime/onnxruntime_cxx_api.h" ] && [ -f "/usr/local/lib/libonnxruntime.so" ]; then
    echo "✓ ONNX Runtime 已经安装"
    echo "头文件: /usr/local/include/onnxruntime/"
    echo "库文件: /usr/local/lib/libonnxruntime.so"
    
    # 显示版本信息
    if command -v strings &> /dev/null; then
        VERSION_INFO=$(strings /usr/local/lib/libonnxruntime.so | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | head -1 || echo "未知")
        echo "已安装版本: $VERSION_INFO"
    fi
    
    read -p "是否要重新安装? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "跳过安装。"
        exit 0
    fi
fi

# 检查必要工具
echo "正在检查必要工具..."

if ! command -v wget &> /dev/null && ! command -v curl &> /dev/null; then
    echo "错误: 需要 wget 或 curl 来下载文件"
    echo "安装命令:"
    echo "  Ubuntu/Debian: sudo apt install wget"
    echo "  CentOS/RHEL:   sudo yum install wget"
    echo "  Arch Linux:    sudo pacman -S wget"
    exit 1
fi

if ! command -v tar &> /dev/null; then
    echo "错误: 需要 tar 来解压文件"
    exit 1
fi

# 创建临时目录
TEMP_DIR="/tmp/onnxruntime_install_$$"
mkdir -p "$TEMP_DIR"
cd "$TEMP_DIR"

echo "临时目录: $TEMP_DIR"

# 下载ONNX Runtime
echo "正在下载 ONNX Runtime..."
if command -v wget &> /dev/null; then
    wget -O "${PACKAGE_NAME}.tgz" "$DOWNLOAD_URL" --progress=bar:force
elif command -v curl &> /dev/null; then
    curl -L -o "${PACKAGE_NAME}.tgz" "$DOWNLOAD_URL" --progress-bar
fi

# 验证下载
if [ ! -f "${PACKAGE_NAME}.tgz" ]; then
    echo "错误: 下载失败"
    exit 1
fi

FILE_SIZE=$(du -h "${PACKAGE_NAME}.tgz" | cut -f1)
echo "下载完成，文件大小: $FILE_SIZE"

# 解压
echo "正在解压..."
tar -xzf "${PACKAGE_NAME}.tgz"

if [ ! -d "$PACKAGE_NAME" ]; then
    echo "错误: 解压失败，找不到目录 $PACKAGE_NAME"
    exit 1
fi

# 进入解压目录
cd "$PACKAGE_NAME"

# 显示包内容
echo "包内容:"
ls -la

# 安装到系统目录
echo "正在安装到系统目录..."

# 安装头文件
echo "安装头文件到 /usr/local/include/onnxruntime/"
sudo mkdir -p /usr/local/include/onnxruntime
sudo cp -r include/* /usr/local/include/onnxruntime/

# 安装库文件
echo "安装库文件到 /usr/local/lib/"
sudo cp lib/libonnxruntime.so* /usr/local/lib/

# 设置库文件权限
sudo chmod 644 /usr/local/lib/libonnxruntime.so*

# 创建符号链接
cd /usr/local/lib
sudo ldconfig

# 验证安装
echo "验证安装..."
if [ -f "/usr/local/include/onnxruntime/onnxruntime_cxx_api.h" ]; then
    echo "✓ 头文件安装成功"
else
    echo "✗ 头文件安装失败"
fi

if [ -f "/usr/local/lib/libonnxruntime.so" ]; then
    echo "✓ 库文件安装成功"
    # 显示库信息
    echo "库文件信息:"
    ls -la /usr/local/lib/libonnxruntime.so*
else
    echo "✗ 库文件安装失败"
fi

# 更新动态链接库缓存
echo "更新动态链接库缓存..."
sudo ldconfig

# 测试库是否可以找到
if ldconfig -p | grep -q onnxruntime; then
    echo "✓ 动态链接库配置成功"
else
    echo "⚠ 动态链接库可能配置有问题"
fi

# 清理临时文件
echo "清理临时文件..."
cd /
rm -rf "$TEMP_DIR"

echo ""
echo "✓ ONNX Runtime 安装完成！"
echo ""
echo "安装位置:"
echo "  头文件: /usr/local/include/onnxruntime/"
echo "  库文件: /usr/local/lib/libonnxruntime.so"
echo ""
echo "现在可以编译和运行 YOLOv8 项目了："
echo "  ./build.sh"
echo ""

# 提供卸载说明
echo "卸载说明:"
echo "如需卸载，请运行以下命令:"
echo "  sudo rm -rf /usr/local/include/onnxruntime"
echo "  sudo rm -f /usr/local/lib/libonnxruntime.so*"
echo "  sudo ldconfig"
